#!/usr/bin/python3

from collections import Counter
from time import sleep

inp=[]
noShoes=int(input('Enter No Of Shoe Sizes:-'))
for i in range(0,noShoes):
      inp.append(int(input('Enter A Shoe Size:-')))

c=Counter(inp)

noCust=int(input('Enter the No Of Customer Willing to Buy Shoes:-'))
'''
print ('*' * 40)
print ('NO OF SHOES PRESENT:-',noShoes)
print ('NO OF CUSTOMERS:-',noCust)
print ('The Shoe Sizes Entered Are:-',list(c.elements()))
print ('*' * 40)
'''

s=Counter()
p=[]
total=0
for i in range(noCust):

    temp=input('Enter Shoe Size and Its Price You are Willing to Pay, separated by ONE SPACE:-')
    temp=temp.split(' ')
    print ('SIZE AND ITS PRICE:-',int(temp[0]),':',int(temp[1]))
    if len(temp) == 2:
       try:
          size,price=int(temp[0]),int(temp[1])
          s[size]+=1
          p.append(price)
          print ('THE PRICE AND SIZES :-', s,p)
          size,price=int(temp[0]),int(temp[1])
       except:
          print ('Please Enter Only Integer Values for Size and Its Price....')

print ('\n' *2)
print ('*' * 40)
print ('NO OF SHOES PRESENT:-',noShoes)
print ('NO OF CUSTOMERS:-',noCust)
print ('The Shoe Sizes Entered Are:-',list(c.elements()))
print ('THE SIZE Counter:-', s)
print ('The Price Counter:-',p)
print ('*' * 40)
print ('\n' *2)
sleep(20)

l=list(s.elements())
print (len(l), l)
for i in range(0,len(l)):
    print ('*' * 40,end='\n')
    print ('Starting the loop ....')
    for j in c:
        if l[i]==j and c[j]!= 0:
           print ('Price "{0}" for Size "{1}"'.format(p[i],l[i]))
           total+=p[i]
           print('FOUND SHOE SIZE "{0}".TOTAL PRICE NOW "{1}"'.format(l[i],total))
           c[j]-=1
           print ('SHOE SIZE "{0}" IS REDUCED BY 1. THE NEW LIST "{1}"'.format(j,c))
        
